-- Auto-generated 2026-05-01 20:28 UTC
-- Live Vahdam collections scraped from public Shopify endpoints
-- Run: paste into Supabase Dashboard -> SQL Editor

INSERT INTO public.vahdam_collections (market, handle, title, description, url) VALUES
  ('US', 'ashwagandha-coffee', '#1 Rated Ashwagandha Coffee', '', 'https://www.vahdam.com/collections/ashwagandha-coffee'),
  ('US', '2026-first-flush', '2026 First Flush', '', 'https://www.vahdam.com/collections/2026-first-flush'),
  ('US', 'advent-calendar-2025', 'Advent Calendar 2025', '', 'https://www.vahdam.com/collections/advent-calendar-2025'),
  ('US', 'all', 'All Products', '', 'https://www.vahdam.com/collections/all'),
  ('US', 'back-to-school-save-20', 'Back to School – Save $20', '', 'https://www.vahdam.com/collections/back-to-school-save-20'),
  ('US', 'back-to-school-save-40', 'Back to School – Save $40', '', 'https://www.vahdam.com/collections/back-to-school-save-40'),
  ('US', 'best-sellers', 'Best Sellers', '', 'https://www.vahdam.com/collections/best-sellers'),
  ('US', 'black-teas', 'Black Teas', '', 'https://www.vahdam.com/collections/black-teas'),
  ('US', 'caffeinated-teas', 'Caffeinated Teas', '', 'https://www.vahdam.com/collections/caffeinated-teas'),
  ('US', 'caffeine-free-teas', 'Caffeine Free Teas', '', 'https://www.vahdam.com/collections/caffeine-free-teas'),
  ('US', 'chai-teas', 'Chai Teas', '', 'https://www.vahdam.com/collections/chai-teas'),
  ('US', 'teas-gifts', 'Daily Rituals', '', 'https://www.vahdam.com/collections/teas-gifts'),
  ('US', 'deal-of-the-day', 'Deal of the day', '', 'https://www.vahdam.com/collections/deal-of-the-day'),
  ('US', 'find-your-balance', 'Find Your Balance', '', 'https://www.vahdam.com/collections/find-your-balance'),
  ('US', 'first-flush-2025', 'First Flush 2025', '', 'https://www.vahdam.com/collections/first-flush-2025'),
  ('US', 'gifts-cards', 'Gifts Cards', '', 'https://www.vahdam.com/collections/gifts-cards'),
  ('US', 'gift-under-30', 'Gifts under $30', '', 'https://www.vahdam.com/collections/gift-under-30'),
  ('US', 'glassware', 'Glassware', '', 'https://www.vahdam.com/collections/glassware'),
  ('US', 'green-teas', 'Green Teas', '', 'https://www.vahdam.com/collections/green-teas'),
  ('US', 'herbal-supplements', 'Herbal Supplements', '', 'https://www.vahdam.com/collections/herbal-supplements'),
  ('US', 'herbal-teas', 'Herbal Teas', '', 'https://www.vahdam.com/collections/herbal-teas'),
  ('US', 'herbal-tea-loose-leaf', 'Herbal Teas | Loose Leaf', '', 'https://www.vahdam.com/collections/herbal-tea-loose-leaf'),
  ('US', 'iced-brews', 'Iced Brews', '', 'https://www.vahdam.com/collections/iced-brews'),
  ('US', 'iced-tea', 'Iced Teas', '', 'https://www.vahdam.com/collections/iced-tea'),
  ('US', 'instant-tea', 'Instant Mixes', '', 'https://www.vahdam.com/collections/instant-tea'),
  ('US', 'insulated-teaware', 'Insulated Teaware', '', 'https://www.vahdam.com/collections/insulated-teaware'),
  ('US', 'latte-instant-premix', 'Lattes', '', 'https://www.vahdam.com/collections/latte-instant-premix'),
  ('US', 'sale', 'LIMITED TIME SALE', '', 'https://www.vahdam.com/collections/sale'),
  ('US', 'limited-time-savings', 'Limited-Time Savings', '', 'https://www.vahdam.com/collections/limited-time-savings'),
  ('US', 'loose-leaf-teas', 'Loose Leaf Teas', '', 'https://www.vahdam.com/collections/loose-leaf-teas'),
  ('US', 'loose-leaf-teas-for-families', 'Loose Leaf Teas for Families', '', 'https://www.vahdam.com/collections/loose-leaf-teas-for-families'),
  ('US', 'masala-teas', 'Masala Teas', '', 'https://www.vahdam.com/collections/masala-teas'),
  ('US', 'matcha', 'Matcha', '', 'https://www.vahdam.com/collections/matcha'),
  ('US', 'new-arrivals', 'New Arrivals', '', 'https://www.vahdam.com/collections/new-arrivals'),
  ('US', 'oolong-teas', 'Oolong Teas', '', 'https://www.vahdam.com/collections/oolong-teas'),
  ('US', 'samplers', 'Samplers', '', 'https://www.vahdam.com/collections/samplers'),
  ('US', 'second-flush-2025', 'Second Flush 2025', '', 'https://www.vahdam.com/collections/second-flush-2025'),
  ('US', 'best-selling-march-2026', 'Shop Our Most Popular Picks', '', 'https://www.vahdam.com/collections/best-selling-march-2026'),
  ('US', 'single-estate-teas', 'Single Estate Teas 2025', '', 'https://www.vahdam.com/collections/single-estate-teas'),
  ('US', 'single-estate-teas-2026', 'Single Estate Teas 2026', '', 'https://www.vahdam.com/collections/single-estate-teas-2026'),
  ('US', 'spices', 'Single Origin Spices', '', 'https://www.vahdam.com/collections/spices'),
  ('US', 'stainless-steel-teaware', 'Stainless Steel Teaware', '', 'https://www.vahdam.com/collections/stainless-steel-teaware'),
  ('US', 'steep-into-spring', 'Steep Into Spring 🌿', '', 'https://www.vahdam.com/collections/steep-into-spring'),
  ('US', 'super-saver-bundles', 'Super Saver Bundles', '', 'https://www.vahdam.com/collections/super-saver-bundles'),
  ('US', 'tea-wares', 'Tea Accessories', '', 'https://www.vahdam.com/collections/tea-wares'),
  ('US', 'long-leaf-tea-bags', 'Tea Bags', '', 'https://www.vahdam.com/collections/long-leaf-tea-bags'),
  ('US', 'tea-pods', 'Tea Pods', '', 'https://www.vahdam.com/collections/tea-pods'),
  ('US', 'teas-by-form', 'Teas By Form', '', 'https://www.vahdam.com/collections/teas-by-form'),
  ('US', 'teas-by-type', 'Teas By Type', '', 'https://www.vahdam.com/collections/teas-by-type'),
  ('US', 'teas-more', 'Teas More', '', 'https://www.vahdam.com/collections/teas-more'),
  ('US', 'gifts', 'The Tea Sets Loved Around The World', '', 'https://www.vahdam.com/collections/gifts'),
  ('US', 'turmeric-teas', 'Turmeric Teas', '', 'https://www.vahdam.com/collections/turmeric-teas'),
  ('US', 'white-teas', 'White Teas', '', 'https://www.vahdam.com/collections/white-teas'),
  ('US', 'winter-teas', 'Winter Teas', '', 'https://www.vahdam.com/collections/winter-teas'),
  ('UK', 'ashwagandha-coffee', '#1 Rated Ashwagandha Coffee', '', 'https://www.vahdam.co.uk/collections/ashwagandha-coffee'),
  ('UK', '2026-first-flush', '2026 First Flush', '', 'https://www.vahdam.co.uk/collections/2026-first-flush'),
  ('UK', 'advent-calendar', 'Advent Calendar 2025', '', 'https://www.vahdam.co.uk/collections/advent-calendar'),
  ('UK', 'all', 'All Products', '', 'https://www.vahdam.co.uk/collections/all'),
  ('UK', 'ashwagandha-goodness', 'ashwagandha-goodness', '', 'https://www.vahdam.co.uk/collections/ashwagandha-goodness'),
  ('UK', 'assam-black-teas', 'Assam Black Teas', '', 'https://www.vahdam.co.uk/collections/assam-black-teas'),
  ('UK', 'assam-second-flush', 'assam-second-flush', '', 'https://www.vahdam.co.uk/collections/assam-second-flush'),
  ('UK', 'assorted-tea-bags', 'Assorted Tea Bags', '', 'https://www.vahdam.co.uk/collections/assorted-tea-bags'),
  ('UK', 'assorted-gift-sampler-sets', 'assorted-gift-sampler-sets', '', 'https://www.vahdam.co.uk/collections/assorted-gift-sampler-sets'),
  ('UK', 'assorted-sampler-gifts', 'assorted-sampler-gifts', '', 'https://www.vahdam.co.uk/collections/assorted-sampler-gifts'),
  ('UK', 'assorted-tea-collection', 'assorted-tea-collection', '', 'https://www.vahdam.co.uk/collections/assorted-tea-collection'),
  ('UK', 'atimas-favorite-teas', 'atimas-favorite-teas', '', 'https://www.vahdam.co.uk/collections/atimas-favorite-teas'),
  ('UK', 'atimas-favourite-holiday-teas', 'atimas-favourite-holiday-teas', '', 'https://www.vahdam.co.uk/collections/atimas-favourite-holiday-teas'),
  ('UK', 'autumn-flush-black-teas', 'Autumn Flush Black Teas', '', 'https://www.vahdam.co.uk/collections/autumn-flush-black-teas'),
  ('UK', 'autumn-teas', 'autumn-teas', '', 'https://www.vahdam.co.uk/collections/autumn-teas'),
  ('UK', 'barbaras-favorite-teas', 'barbaras-favorite-teas', '', 'https://www.vahdam.co.uk/collections/barbaras-favorite-teas'),
  ('UK', 'barbenheimer', 'barbenheimer', '', 'https://www.vahdam.co.uk/collections/barbenheimer'),
  ('UK', 'best-sellers', 'Best Sellers', '', 'https://www.vahdam.co.uk/collections/best-sellers'),
  ('UK', 'bfcm-sale-advent', 'bfcm-sale-advent', '', 'https://www.vahdam.co.uk/collections/bfcm-sale-advent'),
  ('UK', 'bfcm-sale-teas', 'bfcm-sale-teas', '', 'https://www.vahdam.co.uk/collections/bfcm-sale-teas'),
  ('UK', 'bfcm-upto50', 'bfcm-upto50', '', 'https://www.vahdam.co.uk/collections/bfcm-upto50'),
  ('UK', 'black', 'Black', '', 'https://www.vahdam.co.uk/collections/black'),
  ('UK', 'black-tea-bags', 'Black Tea Bags', '', 'https://www.vahdam.co.uk/collections/black-tea-bags'),
  ('UK', 'black-teas', 'Black Teas', '', 'https://www.vahdam.co.uk/collections/black-teas'),
  ('UK', 'black-tea-loose-leaf', 'Black Teas | Loose Leaf', '', 'https://www.vahdam.co.uk/collections/black-tea-loose-leaf'),
  ('UK', 'black-friday-flat-30-off', 'black-friday-flat-30-off', '', 'https://www.vahdam.co.uk/collections/black-friday-flat-30-off'),
  ('UK', 'black-friday-sale-2023', 'black-friday-sale-2023', '', 'https://www.vahdam.co.uk/collections/black-friday-sale-2023'),
  ('UK', 'black-fruity', 'black-fruity', '', 'https://www.vahdam.co.uk/collections/black-fruity'),
  ('UK', 'black-medium', 'black-medium', '', 'https://www.vahdam.co.uk/collections/black-medium'),
  ('UK', 'black-nutty', 'black-nutty', '', 'https://www.vahdam.co.uk/collections/black-nutty'),
  ('UK', 'black-strong', 'black-strong', '', 'https://www.vahdam.co.uk/collections/black-strong'),
  ('UK', 'black-tea-smoky', 'black-tea-smoky', '', 'https://www.vahdam.co.uk/collections/black-tea-smoky'),
  ('UK', 'black-teas-code', 'black-teas-code', '', 'https://www.vahdam.co.uk/collections/black-teas-code'),
  ('UK', 'black-teas-loose-leaf-fb', 'black-teas-loose-leaf-fb', '', 'https://www.vahdam.co.uk/collections/black-teas-loose-leaf-fb'),
  ('UK', 'black-teas-loose-leaf-gm', 'black-teas-loose-leaf-gm', '', 'https://www.vahdam.co.uk/collections/black-teas-loose-leaf-gm'),
  ('UK', 'bof-bestsellers', 'bof-bestsellers', '', 'https://www.vahdam.co.uk/collections/bof-bestsellers'),
  ('UK', 'breakfast-teas', 'breakfast-teas', '', 'https://www.vahdam.co.uk/collections/breakfast-teas'),
  ('UK', 'build-your-own-bundle', 'build-your-own-bundle', '', 'https://www.vahdam.co.uk/collections/build-your-own-bundle'),
  ('UK', 'buy-2-get-1-holiday-special-offer', 'buy-2-get-1-holiday-special-offer', '', 'https://www.vahdam.co.uk/collections/buy-2-get-1-holiday-special-offer'),
  ('UK', 'caffeine-free', 'caffeine-free', '', 'https://www.vahdam.co.uk/collections/caffeine-free'),
  ('UK', 'caffeine-free-1', 'caffeine-free-1', '', 'https://www.vahdam.co.uk/collections/caffeine-free-1'),
  ('UK', 'caffeine-free-teas', 'caffeine-free-teas', '', 'https://www.vahdam.co.uk/collections/caffeine-free-teas'),
  ('UK', 'canada-free-gift', 'canada-free-gift', '', 'https://www.vahdam.co.uk/collections/canada-free-gift'),
  ('UK', 'canada-products', 'canada-products', '', 'https://www.vahdam.co.uk/collections/canada-products'),
  ('UK', 'cardamom', 'cardamom', '', 'https://www.vahdam.co.uk/collections/cardamom'),
  ('UK', 'celebrity-favourite-gifts', 'Celebrity Favourite Gifts', '', 'https://www.vahdam.co.uk/collections/celebrity-favourite-gifts'),
  ('UK', 'ceramic-range', 'ceramic-range', '', 'https://www.vahdam.co.uk/collections/ceramic-range'),
  ('UK', 'chai-teas', 'Chai Teas', '', 'https://www.vahdam.co.uk/collections/chai-teas'),
  ('UK', 'chai-tea-loose-leaf', 'Chai Teas | Loose Leaf', '', 'https://www.vahdam.co.uk/collections/chai-tea-loose-leaf'),
  ('UK', 'chai-latte', 'chai-latte', '', 'https://www.vahdam.co.uk/collections/chai-latte'),
  ('UK', 'chai-strong', 'chai-strong', '', 'https://www.vahdam.co.uk/collections/chai-strong'),
  ('UK', 'chai-teas-code', 'chai-teas-code', '', 'https://www.vahdam.co.uk/collections/chai-teas-code'),
  ('UK', 'chai-teas-loose-leaf-fb', 'chai-teas-loose-leaf-fb', '', 'https://www.vahdam.co.uk/collections/chai-teas-loose-leaf-fb'),
  ('UK', 'chai-teas-loose-leaf-gm', 'chai-teas-loose-leaf-gm', '', 'https://www.vahdam.co.uk/collections/chai-teas-loose-leaf-gm'),
  ('UK', 'chai-teas-medium', 'chai-teas-medium', '', 'https://www.vahdam.co.uk/collections/chai-teas-medium'),
  ('UK', 'chai-teas-nutty', 'chai-teas-nutty', '', 'https://www.vahdam.co.uk/collections/chai-teas-nutty'),
  ('UK', 'chai-teas-spicy', 'chai-teas-spicy', '', 'https://www.vahdam.co.uk/collections/chai-teas-spicy'),
  ('UK', 'christmas-gifts', 'Christmas Gifts', '', 'https://www.vahdam.co.uk/collections/christmas-gifts'),
  ('UK', 'christmas-sale', 'christmas-sale', '', 'https://www.vahdam.co.uk/collections/christmas-sale'),
  ('UK', 'cinnamon-specials', 'cinnamon-specials', '', 'https://www.vahdam.co.uk/collections/cinnamon-specials'),
  ('UK', 'cinnamon-teas', 'cinnamon-teas', '', 'https://www.vahdam.co.uk/collections/cinnamon-teas'),
  ('UK', 'classic-gifts', 'Classic Gifts', '', 'https://www.vahdam.co.uk/collections/classic-gifts'),
  ('UK', 'cocoa-specials', 'cocoa-specials', '', 'https://www.vahdam.co.uk/collections/cocoa-specials'),
  ('UK', 'coral', 'Coral', '', 'https://www.vahdam.co.uk/collections/coral'),
  ('UK', 'sale', 'Cyber Monday Sale', '', 'https://www.vahdam.co.uk/collections/sale'),
  ('UK', 'cyber-monday-sale-2023', 'Cyber Monday Sale 2023', '', 'https://www.vahdam.co.uk/collections/cyber-monday-sale-2023'),
  ('UK', 'darjeeling-first-flush-2023', 'Darjeeling First Flush - 2023', '', 'https://www.vahdam.co.uk/collections/darjeeling-first-flush-2023'),
  ('UK', 'darjeeling-second-flush', 'darjeeling-second-flush', '', 'https://www.vahdam.co.uk/collections/darjeeling-second-flush'),
  ('UK', 'darjeeling-teas-gm', 'darjeeling-teas-gm', '', 'https://www.vahdam.co.uk/collections/darjeeling-teas-gm'),
  ('UK', 'deal-of-the-day-hidden', 'deal-of-the-day-hidden', '', 'https://www.vahdam.co.uk/collections/deal-of-the-day-hidden'),
  ('UK', 'discount', 'discount', '', 'https://www.vahdam.co.uk/collections/discount'),
  ('UK', 'discount-collection', 'discount-collection', '', 'https://www.vahdam.co.uk/collections/discount-collection'),
  ('UK', 'dooars-black-teas', 'Dooars Black Teas', '', 'https://www.vahdam.co.uk/collections/dooars-black-teas'),
  ('UK', 'dooars-teas', 'Dooars Teas', '', 'https://www.vahdam.co.uk/collections/dooars-teas'),
  ('UK', 'drinkware-gifts', 'Drinkware Gifts', '', 'https://www.vahdam.co.uk/collections/drinkware-gifts'),
  ('UK', 'energy', 'energy', '', 'https://www.vahdam.co.uk/collections/energy'),
  ('UK', 'entire-tea-accessories', 'entire-tea-accessories', '', 'https://www.vahdam.co.uk/collections/entire-tea-accessories'),
  ('UK', 'fall-sale', 'fall-sale', '', 'https://www.vahdam.co.uk/collections/fall-sale'),
  ('UK', 'featured-products', 'featured-products', '', 'https://www.vahdam.co.uk/collections/featured-products'),
  ('UK', 'featured-teas', 'featured-teas', '', 'https://www.vahdam.co.uk/collections/featured-teas'),
  ('UK', 'find-your-balance', 'find-your-balance', '', 'https://www.vahdam.co.uk/collections/find-your-balance'),
  ('UK', 'first-flush-2025', 'First Flush 2025', '', 'https://www.vahdam.co.uk/collections/first-flush-2025'),
  ('UK', 'first-flush-2', 'first-flush-2', '', 'https://www.vahdam.co.uk/collections/first-flush-2'),
  ('UK', 'first-flush-2022', 'first-flush-2022', '', 'https://www.vahdam.co.uk/collections/first-flush-2022'),
  ('UK', 'founders-favorites', 'founders-favorites', '', 'https://www.vahdam.co.uk/collections/founders-favorites'),
  ('UK', 'functional-detox-ingredients', 'functional-detox-ingredients', '', 'https://www.vahdam.co.uk/collections/functional-detox-ingredients'),
  ('UK', 'germany-bestsellers', 'germany-bestsellers', '', 'https://www.vahdam.co.uk/collections/germany-bestsellers'),
  ('UK', 'gift-bundles', 'Gift Bundles', '', 'https://www.vahdam.co.uk/collections/gift-bundles'),
  ('UK', 'gift-cards', 'Gift Cards', '', 'https://www.vahdam.co.uk/collections/gift-cards'),
  ('UK', 'gift-bestsellers', 'gift-bestsellers', '', 'https://www.vahdam.co.uk/collections/gift-bestsellers'),
  ('UK', 'gifts-above-75', 'Gifts above 75', '', 'https://www.vahdam.co.uk/collections/gifts-above-75'),
  ('UK', 'gifts-between-25-and-50', 'Gifts between 25 and 50', '', 'https://www.vahdam.co.uk/collections/gifts-between-25-and-50'),
  ('UK', 'gifts-for-her', 'Gifts For Her', '', 'https://www.vahdam.co.uk/collections/gifts-for-her'),
  ('UK', 'gifts-under-30', 'Gifts Under $30', '', 'https://www.vahdam.co.uk/collections/gifts-under-30'),
  ('UK', 'gifts-under-25', 'Gifts Under 25', '', 'https://www.vahdam.co.uk/collections/gifts-under-25'),
  ('UK', 'gifts-between-50-and-75', 'gifts-between-50-and-75', '', 'https://www.vahdam.co.uk/collections/gifts-between-50-and-75'),
  ('UK', 'gifts-for-him', 'gifts-for-him', '', 'https://www.vahdam.co.uk/collections/gifts-for-him'),
  ('UK', 'gifts-under-15', 'gifts-under-15', '', 'https://www.vahdam.co.uk/collections/gifts-under-15'),
  ('UK', 'glassware', 'Glassware', '', 'https://www.vahdam.co.uk/collections/glassware'),
  ('UK', 'green', 'Green', '', 'https://www.vahdam.co.uk/collections/green'),
  ('UK', 'green-tea-bags', 'Green Tea Bags', '', 'https://www.vahdam.co.uk/collections/green-tea-bags'),
  ('UK', 'green-teas', 'Green Teas', '', 'https://www.vahdam.co.uk/collections/green-teas'),
  ('UK', 'green-teas-loose-leaf', 'Green Teas | Loose Leaf', '', 'https://www.vahdam.co.uk/collections/green-teas-loose-leaf'),
  ('UK', 'green-teas-code', 'green-teas-code', '', 'https://www.vahdam.co.uk/collections/green-teas-code'),
  ('UK', 'green-teas-gm', 'green-teas-gm', '', 'https://www.vahdam.co.uk/collections/green-teas-gm'),
  ('UK', 'green-teas-gm-1', 'green-teas-gm-1', '', 'https://www.vahdam.co.uk/collections/green-teas-gm-1'),
  ('UK', 'grocery-collection-page-manual', 'grocery-collection-page-manual', '', 'https://www.vahdam.co.uk/collections/grocery-collection-page-manual'),
  ('UK', 'halloween-exclusive-sale', 'halloween-exclusive-sale', '', 'https://www.vahdam.co.uk/collections/halloween-exclusive-sale'),
  ('UK', 'halloween-exclusives', 'halloween-exclusives', '', 'https://www.vahdam.co.uk/collections/halloween-exclusives'),
  ('UK', 'halloween-sale', 'halloween-sale', '', 'https://www.vahdam.co.uk/collections/halloween-sale'),
  ('UK', 'halloween-savings', 'halloween-savings', '', 'https://www.vahdam.co.uk/collections/halloween-savings'),
  ('UK', 'halloween-treat', 'halloween-treat', '', 'https://www.vahdam.co.uk/collections/halloween-treat'),
  ('UK', 'halloween-treat-1', 'halloween-treat-1', '', 'https://www.vahdam.co.uk/collections/halloween-treat-1'),
  ('UK', 'herbal-supplements', 'Herbal Supplements', '', 'https://www.vahdam.co.uk/collections/herbal-supplements'),
  ('UK', 'herbal-tea', 'Herbal Teas', '', 'https://www.vahdam.co.uk/collections/herbal-tea'),
  ('UK', 'herbal-teas-loose-leaf', 'Herbal Teas | Loose Leaf', '', 'https://www.vahdam.co.uk/collections/herbal-teas-loose-leaf'),
  ('UK', 'herbal-tea-loose-leaf', 'Herbal Teas | Loose Leaf', '', 'https://www.vahdam.co.uk/collections/herbal-tea-loose-leaf'),
  ('UK', 'herbal-tea-bags', 'herbal-tea-bags', '', 'https://www.vahdam.co.uk/collections/herbal-tea-bags'),
  ('UK', 'herbal-tea-code', 'herbal-tea-code', '', 'https://www.vahdam.co.uk/collections/herbal-tea-code'),
  ('UK', 'holiday-deals', 'holiday-deals', '', 'https://www.vahdam.co.uk/collections/holiday-deals'),
  ('UK', 'holiday-specials', 'holiday-specials', '', 'https://www.vahdam.co.uk/collections/holiday-specials'),
  ('UK', 'frontpage', 'Home page', '', 'https://www.vahdam.co.uk/collections/frontpage'),
  ('UK', 'iced-tea', 'Iced Teas', '', 'https://www.vahdam.co.uk/collections/iced-tea'),
  ('UK', 'iced-brews', 'iced-brews', '', 'https://www.vahdam.co.uk/collections/iced-brews'),
  ('UK', 'immunity-boosting-teas', 'immunity-boosting-teas', '', 'https://www.vahdam.co.uk/collections/immunity-boosting-teas'),
  ('UK', 'ingredient-based', 'Ingredient Based', '', 'https://www.vahdam.co.uk/collections/ingredient-based'),
  ('UK', 'instant-tea', 'Instant Mixes', '', 'https://www.vahdam.co.uk/collections/instant-tea'),
  ('UK', 'instant-teas', 'Instant Teas', '', 'https://www.vahdam.co.uk/collections/instant-teas'),
  ('UK', 'instant-chai-latte', 'instant-chai-latte', '', 'https://www.vahdam.co.uk/collections/instant-chai-latte'),
  ('UK', 'insulated-range', 'Insulated range', '', 'https://www.vahdam.co.uk/collections/insulated-range'),
  ('UK', 'insulated-teaware', 'Insulated Teaware', '', 'https://www.vahdam.co.uk/collections/insulated-teaware'),
  ('UK', 'isabellas-favourite-holiday-teas', 'isabellas-favourite-holiday-teas', '', 'https://www.vahdam.co.uk/collections/isabellas-favourite-holiday-teas'),
  ('UK', 'isabelles-favourite-teas', 'isabelles-favourite-teas', '', 'https://www.vahdam.co.uk/collections/isabelles-favourite-teas'),
  ('UK', 'keto-support', 'keto-support', '', 'https://www.vahdam.co.uk/collections/keto-support'),
  ('UK', 'limited-time-savings', 'limited-time-savings', '', 'https://www.vahdam.co.uk/collections/limited-time-savings'),
  ('UK', 'loose-leaf-teas', 'Loose Leaf Teas', '', 'https://www.vahdam.co.uk/collections/loose-leaf-teas'),
  ('UK', 'lunar-new-year', 'lunar-new-year', '', 'https://www.vahdam.co.uk/collections/lunar-new-year'),
  ('UK', 'marias-favourite-teas', 'marias-favourite-teas', '', 'https://www.vahdam.co.uk/collections/marias-favourite-teas'),
  ('UK', 'matcha', 'Matcha', '', 'https://www.vahdam.co.uk/collections/matcha'),
  ('UK', 'mint-green', 'Mint Green', '', 'https://www.vahdam.co.uk/collections/mint-green'),
  ('UK', 'gifts', 'Most-Loved Tea Gifts', '', 'https://www.vahdam.co.uk/collections/gifts'),
  ('UK', 'mothers-day-2022-gift', 'mothers-day-2022-gift', '', 'https://www.vahdam.co.uk/collections/mothers-day-2022-gift'),
  ('UK', 'mothers-day-2025', 'mothers-day-2025', '', 'https://www.vahdam.co.uk/collections/mothers-day-2025'),
  ('UK', 'natalias-favourite-holiday-teas', 'natalias-favourite-holiday-teas', '', 'https://www.vahdam.co.uk/collections/natalias-favourite-holiday-teas'),
  ('UK', 'natalias-favourite-teas', 'natalias-favourite-teas', '', 'https://www.vahdam.co.uk/collections/natalias-favourite-teas'),
  ('UK', 'national-lazy-day', 'national-lazy-day', '', 'https://www.vahdam.co.uk/collections/national-lazy-day'),
  ('UK', 'nepal-black-teas', 'Nepal Black Teas', '', 'https://www.vahdam.co.uk/collections/nepal-black-teas'),
  ('UK', 'new-arrivals', 'new-arrivals', '', 'https://www.vahdam.co.uk/collections/new-arrivals'),
  ('UK', 'nilgiri-teas', 'nilgiri-teas', '', 'https://www.vahdam.co.uk/collections/nilgiri-teas'),
  ('UK', 'occasion-boxes', 'occasion-boxes', '', 'https://www.vahdam.co.uk/collections/occasion-boxes'),
  ('UK', 'olgas-favorite-teas', 'olgas-favorite-teas', '', 'https://www.vahdam.co.uk/collections/olgas-favorite-teas'),
  ('UK', 'oolong-teas', 'Oolong Teas', '', 'https://www.vahdam.co.uk/collections/oolong-teas'),
  ('UK', 'oolong-teas-loose-leaf', 'Oolong Teas | Loose Leaf', '', 'https://www.vahdam.co.uk/collections/oolong-teas-loose-leaf'),
  ('UK', 'oops-we-made-too-much-sale', 'oops-we-made-too-much-sale', '', 'https://www.vahdam.co.uk/collections/oops-we-made-too-much-sale'),
  ('UK', 'oprah-fan-mom', 'oprah-fan-mom', '', 'https://www.vahdam.co.uk/collections/oprah-fan-mom'),
  ('UK', 'opt-wellness', 'opt-wellness', '', 'https://www.vahdam.co.uk/collections/opt-wellness'),
  ('UK', 'opt-wellness-code', 'opt-wellness-code', '', 'https://www.vahdam.co.uk/collections/opt-wellness-code'),
  ('UK', 'organic-black-teas', 'Organic Black Teas', '', 'https://www.vahdam.co.uk/collections/organic-black-teas'),
  ('UK', 'organic-teas', 'Organic Teas', '', 'https://www.vahdam.co.uk/collections/organic-teas'),
  ('UK', 'organic-latte-gm', 'organic-latte-gm', '', 'https://www.vahdam.co.uk/collections/organic-latte-gm'),
  ('UK', 'our-bestsellers-gm', 'our-bestsellers-gm', '', 'https://www.vahdam.co.uk/collections/our-bestsellers-gm'),
  ('UK', 'pink', 'Pink', '', 'https://www.vahdam.co.uk/collections/pink'),
  ('UK', 'pipers-favorite-teas', 'pipers-favorite-teas', '', 'https://www.vahdam.co.uk/collections/pipers-favorite-teas'),
  ('UK', 'prime-day-sale', 'prime-day-sale', '', 'https://www.vahdam.co.uk/collections/prime-day-sale'),
  ('UK', 'pumpkin-specials', 'pumpkin-specials', '', 'https://www.vahdam.co.uk/collections/pumpkin-specials'),
  ('UK', 'rachels-favorite-teas', 'rachels-favorite-teas', '', 'https://www.vahdam.co.uk/collections/rachels-favorite-teas'),
  ('UK', 'robins-favourite-teas', 'robins-favourite-teas', '', 'https://www.vahdam.co.uk/collections/robins-favourite-teas'),
  ('UK', 'sahara-rose', 'sahara-rose', '', 'https://www.vahdam.co.uk/collections/sahara-rose'),
  ('UK', 'samplers', 'Samplers', '', 'https://www.vahdam.co.uk/collections/samplers'),
  ('UK', 'seasonal-change-teas', 'seasonal-change-teas', '', 'https://www.vahdam.co.uk/collections/seasonal-change-teas'),
  ('UK', 'second-flush-2025', 'Second Flush 2025', '', 'https://www.vahdam.co.uk/collections/second-flush-2025'),
  ('UK', 'second-flush-teas-2023', 'Second Flush Black Teas 2023', '', 'https://www.vahdam.co.uk/collections/second-flush-teas-2023'),
  ('UK', 'second-flush', 'second-flush', '', 'https://www.vahdam.co.uk/collections/second-flush'),
  ('UK', 'second-flush-sale', 'second-flush-sale', '', 'https://www.vahdam.co.uk/collections/second-flush-sale'),
  ('UK', 'sellers', 'sellers', '', 'https://www.vahdam.co.uk/collections/sellers'),
  ('UK', 'best-selling-march-2026', 'Shop Our Most Popular Picks', '', 'https://www.vahdam.co.uk/collections/best-selling-march-2026'),
  ('UK', 'shop-our-bestsellers', 'shop-our-bestsellers', '', 'https://www.vahdam.co.uk/collections/shop-our-bestsellers'),
  ('UK', 'signature-private-reserve', 'Signature Private Reserve', '', 'https://www.vahdam.co.uk/collections/signature-private-reserve'),
  ('UK', 'single-estate', 'Single Estate', '', 'https://www.vahdam.co.uk/collections/single-estate'),
  ('UK', 'single-estate-teas', 'Single Estate Teas 2025', '', 'https://www.vahdam.co.uk/collections/single-estate-teas'),
  ('UK', 'spices', 'Single Origin Spices', '', 'https://www.vahdam.co.uk/collections/spices'),
  ('UK', 'skys-the-limit', 'skys-the-limit', '', 'https://www.vahdam.co.uk/collections/skys-the-limit'),
  ('UK', 'solanges-favourite-holiday-teas', 'solanges-favourite-holiday-teas', '', 'https://www.vahdam.co.uk/collections/solanges-favourite-holiday-teas'),
  ('UK', 'solanges-favourite-teas', 'solanges-favourite-teas', '', 'https://www.vahdam.co.uk/collections/solanges-favourite-teas'),
  ('UK', 'solanges-favourite-teas-1', 'solanges-favourite-teas-1', '', 'https://www.vahdam.co.uk/collections/solanges-favourite-teas-1'),
  ('UK', 'spring-teas', 'spring-teas', '', 'https://www.vahdam.co.uk/collections/spring-teas'),
  ('UK', 'st-patricks-day-bestsellers', 'st-patricks-day-bestsellers', '', 'https://www.vahdam.co.uk/collections/st-patricks-day-bestsellers'),
  ('UK', 'st-patricks-day-black-teas', 'st-patricks-day-black-teas', '', 'https://www.vahdam.co.uk/collections/st-patricks-day-black-teas'),
  ('UK', 'st-patricks-day-chai-teas', 'st-patricks-day-chai-teas', '', 'https://www.vahdam.co.uk/collections/st-patricks-day-chai-teas'),
  ('UK', 'stainless-steel-range', 'Stainless Steel Range', '', 'https://www.vahdam.co.uk/collections/stainless-steel-range'),
  ('UK', 'stainless-steel-teaware', 'Stainless Steel Teaware', '', 'https://www.vahdam.co.uk/collections/stainless-steel-teaware'),
  ('UK', 'steep-into-spring', 'steep-into-spring', '', 'https://www.vahdam.co.uk/collections/steep-into-spring'),
  ('UK', 'super-saver-bundles', 'Super Saver Bundles', '', 'https://www.vahdam.co.uk/collections/super-saver-bundles'),
  ('UK', 'superfoods', 'superfoods', '', 'https://www.vahdam.co.uk/collections/superfoods'),
  ('UK', 'susans-favourite-holiday-teas', 'susans-favourite-holiday-teas', '', 'https://www.vahdam.co.uk/collections/susans-favourite-holiday-teas'),
  ('UK', 'tea-accessories', 'Tea Accessories', '', 'https://www.vahdam.co.uk/collections/tea-accessories'),
  ('UK', 'tea-bags', 'Tea Bags', '', 'https://www.vahdam.co.uk/collections/tea-bags'),
  ('UK', 'tea-carnival-collection', 'Tea Carnival Collection', '', 'https://www.vahdam.co.uk/collections/tea-carnival-collection'),
  ('UK', 'tea-pods', 'Tea Pods', '', 'https://www.vahdam.co.uk/collections/tea-pods'),
  ('UK', 'tea-lover-mom', 'tea-lover-mom', '', 'https://www.vahdam.co.uk/collections/tea-lover-mom'),
  ('UK', 'travel-collection', 'Travel Collection', '', 'https://www.vahdam.co.uk/collections/travel-collection'),
  ('UK', 'traveller-mom', 'traveller-mom', '', 'https://www.vahdam.co.uk/collections/traveller-mom'),
  ('UK', 'trendy-mom', 'trendy-mom', '', 'https://www.vahdam.co.uk/collections/trendy-mom'),
  ('UK', 'turmeric-collection', 'Turmeric Collection', '', 'https://www.vahdam.co.uk/collections/turmeric-collection'),
  ('UK', 'turmeric-ginger', 'turmeric-ginger', '', 'https://www.vahdam.co.uk/collections/turmeric-ginger'),
  ('UK', 'turmeric-herbal-teas-fb', 'turmeric-herbal-teas-fb', '', 'https://www.vahdam.co.uk/collections/turmeric-herbal-teas-fb'),
  ('UK', 'turmeric-herbal-teas-gm', 'turmeric-herbal-teas-gm', '', 'https://www.vahdam.co.uk/collections/turmeric-herbal-teas-gm'),
  ('UK', 'turmeric-latte-fb', 'turmeric-latte-fb', '', 'https://www.vahdam.co.uk/collections/turmeric-latte-fb'),
  ('UK', 'turmeric-superfood-lattes', 'turmeric-superfood-lattes', '', 'https://www.vahdam.co.uk/collections/turmeric-superfood-lattes'),
  ('UK', 'uk-free-gift', 'uk-free-gift', '', 'https://www.vahdam.co.uk/collections/uk-free-gift'),
  ('UK', 'uk-products', 'uk-products', '', 'https://www.vahdam.co.uk/collections/uk-products'),
  ('UK', 'vahdam-red', 'vahdam-red', '', 'https://www.vahdam.co.uk/collections/vahdam-red'),
  ('UK', 'vahdam-women-favs', 'vahdam-women-favs', '', 'https://www.vahdam.co.uk/collections/vahdam-women-favs'),
  ('UK', 'valentine-sale', 'valentine-sale', '', 'https://www.vahdam.co.uk/collections/valentine-sale'),
  ('UK', 'vegan', 'vegan', '', 'https://www.vahdam.co.uk/collections/vegan'),
  ('UK', 'vegan-1', 'vegan-1', '', 'https://www.vahdam.co.uk/collections/vegan-1'),
  ('UK', 'wellness-digest', 'wellness-digest', '', 'https://www.vahdam.co.uk/collections/wellness-digest'),
  ('UK', 'wellness-enthusiast', 'wellness-enthusiast', '', 'https://www.vahdam.co.uk/collections/wellness-enthusiast'),
  ('UK', 'wellness-savings-carnival', 'wellness-savings-carnival', '', 'https://www.vahdam.co.uk/collections/wellness-savings-carnival'),
  ('UK', 'white-teas', 'White Teas', '', 'https://www.vahdam.co.uk/collections/white-teas'),
  ('UK', 'white-teas-loose-leaf', 'White Teas | Loose Leaf', '', 'https://www.vahdam.co.uk/collections/white-teas-loose-leaf'),
  ('UK', 'winter-teas', 'Winter Teas', '', 'https://www.vahdam.co.uk/collections/winter-teas'),
  ('UK', 'winter-classics', 'winter-classics', '', 'https://www.vahdam.co.uk/collections/winter-classics'),
  ('UK', 'yellow', 'yellow', '', 'https://www.vahdam.co.uk/collections/yellow'),
  ('UK', 'yogaclub', 'yogaclub', '', 'https://www.vahdam.co.uk/collections/yogaclub'),
  ('UK', 'zodiac-collection', 'zodiac-collection', '', 'https://www.vahdam.co.uk/collections/zodiac-collection'),
  ('IN', 'founders-day', 'A Decade of Wellness, Impact & Innovation', '', 'https://www.vahdam.in/collections/founders-day'),
  ('IN', 'accessories', 'Accessories', '', 'https://www.vahdam.in/collections/accessories'),
  ('IN', 'all', 'All Products', '', 'https://www.vahdam.in/collections/all'),
  ('IN', 'all-teas-copy', 'All Teas', '', 'https://www.vahdam.in/collections/all-teas-copy'),
  ('IN', 'best-sellers', 'Best Sellers', '', 'https://www.vahdam.in/collections/best-sellers'),
  ('IN', 'black-teas', 'Black Teas', '', 'https://www.vahdam.in/collections/black-teas'),
  ('IN', 'bundle-collections', 'Bundle-Collection', '', 'https://www.vahdam.in/collections/bundle-collections'),
  ('IN', 'chai-teas', 'Chai Teas', '', 'https://www.vahdam.in/collections/chai-teas'),
  ('IN', 'chamomile-teas', 'Chamomile Teas', '', 'https://www.vahdam.in/collections/chamomile-teas'),
  ('IN', 'deal-of-the-day', 'Deal of the Day', '', 'https://www.vahdam.in/collections/deal-of-the-day'),
  ('IN', 'first-flush-2025', 'First Flush 2026', '', 'https://www.vahdam.in/collections/first-flush-2025'),
  ('IN', 'glassware', 'Glassware', '', 'https://www.vahdam.in/collections/glassware'),
  ('IN', 'green-teas', 'Green Teas', '', 'https://www.vahdam.in/collections/green-teas'),
  ('IN', 'herbal-tea', 'Herbal Infusions', '', 'https://www.vahdam.in/collections/herbal-tea'),
  ('IN', 'holi-the-flavor-fest', 'Holi - The Flavor Fest 🥂', '', 'https://www.vahdam.in/collections/holi-the-flavor-fest'),
  ('IN', 'iced-brews', 'Iced Brews', '', 'https://www.vahdam.in/collections/iced-brews'),
  ('IN', 'iced-teas', 'Iced Teas', '', 'https://www.vahdam.in/collections/iced-teas'),
  ('IN', 'instant-teas', 'Instant Mixes', '', 'https://www.vahdam.in/collections/instant-teas'),
  ('IN', 'insulated-teaware', 'Insulated Teaware', '', 'https://www.vahdam.in/collections/insulated-teaware'),
  ('IN', 'loose-leaf-teas', 'Loose Leaf Teas', '', 'https://www.vahdam.in/collections/loose-leaf-teas'),
  ('IN', 'matcha', 'Matcha Tea Powder', '', 'https://www.vahdam.in/collections/matcha'),
  ('IN', 'buy-tea-sets-in-india', 'Most-Loved Tea Gifts', '', 'https://www.vahdam.in/collections/buy-tea-sets-in-india'),
  ('IN', 'newly-launched', 'Newly Launched', '', 'https://www.vahdam.in/collections/newly-launched'),
  ('IN', 'oolong-teas', 'Oolong Teas', '', 'https://www.vahdam.in/collections/oolong-teas'),
  ('IN', 'samplers', 'Samplers', '', 'https://www.vahdam.in/collections/samplers'),
  ('IN', 'second-flush-2025', 'Second Flush 2025', '', 'https://www.vahdam.in/collections/second-flush-2025'),
  ('IN', 'sale', 'Share the Joy of Freedom and Festivity', '', 'https://www.vahdam.in/collections/sale'),
  ('IN', 'single-estate-2025', 'Single Estate 2026', '', 'https://www.vahdam.in/collections/single-estate-2025'),
  ('IN', 'stainless-steel-teaware', 'Stainless Steel Teaware', '', 'https://www.vahdam.in/collections/stainless-steel-teaware'),
  ('IN', 'supplements', 'Supplements', '', 'https://www.vahdam.in/collections/supplements'),
  ('IN', 'tea-bags', 'Tea Bags', '', 'https://www.vahdam.in/collections/tea-bags'),
  ('IN', 'test-bundle', 'Test Bundle', '', 'https://www.vahdam.in/collections/test-bundle'),
  ('IN', 'test-smart-collection', 'TEST Smart Collection', '', 'https://www.vahdam.in/collections/test-smart-collection'),
  ('IN', 'thoughtful-gifting-bundles', 'Thoughtful Gifting Bundles', '', 'https://www.vahdam.in/collections/thoughtful-gifting-bundles'),
  ('IN', 'trending-products', 'Trending Products', '', 'https://www.vahdam.in/collections/trending-products'),
  ('IN', 'turmeric-collection', 'Turmeric collection', '', 'https://www.vahdam.in/collections/turmeric-collection'),
  ('IN', 'upsell-collection', 'Upsell Collection', '', 'https://www.vahdam.in/collections/upsell-collection'),
  ('IN', 'valentine-all-teas', 'Valentine All Teas', '', 'https://www.vahdam.in/collections/valentine-all-teas'),
  ('IN', 'valentinebundle', 'Valentinebundle', '', 'https://www.vahdam.in/collections/valentinebundle'),
  ('IN', 'white-teas', 'White Teas', '', 'https://www.vahdam.in/collections/white-teas'),
  ('IN', 'winter-essentials', 'Winter Essentials', '', 'https://www.vahdam.in/collections/winter-essentials'),
  ('Global', 'ashwagandha-coffee', '#1 Rated Ashwagandha Coffee', '', 'https://www.vahdam.global/collections/ashwagandha-coffee'),
  ('Global', '2026-first-flush', '2026 First Flush', '', 'https://www.vahdam.global/collections/2026-first-flush'),
  ('Global', 'founders-day', 'A Decade of Wellness, Impact & Innovation', '', 'https://www.vahdam.global/collections/founders-day'),
  ('Global', 'advent-calendar', 'Advent Calendar 2025', '', 'https://www.vahdam.global/collections/advent-calendar'),
  ('Global', 'all', 'All Products', '', 'https://www.vahdam.global/collections/all'),
  ('Global', 'best-sellers', 'Best Sellers Of The Season', '', 'https://www.vahdam.global/collections/best-sellers'),
  ('Global', 'black-teas', 'Black Teas', '', 'https://www.vahdam.global/collections/black-teas'),
  ('Global', 'best-seller-canada', 'Canada''s Most-Loved Blends', '', 'https://www.vahdam.global/collections/best-seller-canada'),
  ('Global', 'chai-teas', 'Chai Teas', '', 'https://www.vahdam.global/collections/chai-teas'),
  ('Global', 'clearance-sale', 'CLEARANCE SALE', '', 'https://www.vahdam.global/collections/clearance-sale'),
  ('Global', 'deal-of-the-day-2024', 'Deal of the day', '', 'https://www.vahdam.global/collections/deal-of-the-day-2024'),
  ('Global', 'first-flush-2025', 'First Flush 2025', '', 'https://www.vahdam.global/collections/first-flush-2025'),
  ('Global', 'best-seller-germany', 'Germany''s Most-Loved Blends', '', 'https://www.vahdam.global/collections/best-seller-germany'),
  ('Global', 'glassware', 'Glassware', '', 'https://www.vahdam.global/collections/glassware'),
  ('Global', 'green-teas', 'Green Teas', '', 'https://www.vahdam.global/collections/green-teas'),
  ('Global', 'herbal-teas', 'Herbal Teas', '', 'https://www.vahdam.global/collections/herbal-teas'),
  ('Global', 'instant-tea', 'Instant Mixes', '', 'https://www.vahdam.global/collections/instant-tea'),
  ('Global', 'drink-ware', 'Insulated Teaware', '', 'https://www.vahdam.global/collections/drink-ware'),
  ('Global', 'insulated-teaware', 'Insulated Teaware', '', 'https://www.vahdam.global/collections/insulated-teaware'),
  ('Global', 'best-seller-italy', 'Italy’s Most-Loved Blends', '', 'https://www.vahdam.global/collections/best-seller-italy'),
  ('Global', 'loose-leaf-teas', 'Loose Leaf Teas', '', 'https://www.vahdam.global/collections/loose-leaf-teas'),
  ('Global', 'matcha', 'Matcha', '', 'https://www.vahdam.global/collections/matcha'),
  ('Global', 'gifts', 'Most Loved Gifts Of The Season', '', 'https://www.vahdam.global/collections/gifts'),
  ('Global', 'new-arrivals', 'New Arrivals', '', 'https://www.vahdam.global/collections/new-arrivals'),
  ('Global', 'oolong-teas', 'Oolong Teas', '', 'https://www.vahdam.global/collections/oolong-teas'),
  ('Global', 'samplers', 'Samplers', '', 'https://www.vahdam.global/collections/samplers'),
  ('Global', 'second-flush-2025', 'Second Flush 2025', '', 'https://www.vahdam.global/collections/second-flush-2025'),
  ('Global', 'single-estate', 'Single Estate 2025', '', 'https://www.vahdam.global/collections/single-estate'),
  ('Global', 'stainless-steel-range', 'Stainless Steel Teaware', '', 'https://www.vahdam.global/collections/stainless-steel-range'),
  ('Global', 'steep-into-spring', 'Steep Into Spring 🌿', '', 'https://www.vahdam.global/collections/steep-into-spring'),
  ('Global', 'sale', 'SUPER SAVER TEA COLLECTION', '', 'https://www.vahdam.global/collections/sale'),
  ('Global', 'tea-wares', 'Tea Accessories', '', 'https://www.vahdam.global/collections/tea-wares'),
  ('Global', 'tea-bags', 'Tea Bags', '', 'https://www.vahdam.global/collections/tea-bags'),
  ('Global', 'best-seller-uk', 'The UK''s Most-Loved Blends', '', 'https://www.vahdam.global/collections/best-seller-uk'),
  ('Global', 'white-teas', 'White Teas', '', 'https://www.vahdam.global/collections/white-teas')
ON CONFLICT (market, handle) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, url=EXCLUDED.url, refreshed_at=now();